version: 2

jobs:
  provider:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install provider dependencies
          command: |
            cd server
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: Run provider tests
          command: |
            cd server
            mkdir -p /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - run:
          name: Verify contracts
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd server
              PUBLISH_VERIFICATION_RESULTS=true rake pact:verify
            fi
      - run:
          name: Deploy provider
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              pact-broker can-i-deploy --pacticipant PaymentService \
                --broker-base-url http://46.101.49.17:8000/ --latest && echo "Deploying provider"
            fi
