version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler -v 2.0.1
            bundle update --bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      - run:
          name: Verify contracts
          command: rake pact:verify

  deploy:
    docker:
      - image: circleci/ruby:2.6.3

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler -v 2.0.1
            bundle update --bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Check if deployment can happen
          command: |
            bundle exec pact-broker can-i-deploy \
              --pacticipant ${PACT_PARTICIPANT} \
              --broker-base-url ${PACT_BROKER_BASE_URL} \
              --latest --to production

      - run:
          name: Deploy to production
          command: |
            echo "Deploying to production"

            bundle exec pact-broker create-version-tag \
              --pacticipant ${PACT_PARTICIPANT} \
              --broker-base-url ${PACT_BROKER_BASE_URL} \
              --version ${CIRCLE_SHA1} \
              --tag production

  verify:
    docker:
      - image: circleci/ruby:2.6.3

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler -v 2.0.1
            bundle update --bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Publish verification results
          command: PUBLISH_VERIFICATION_RESULTS=true rake pact:verify

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - verify:
          requires:
            - deploy
          filters:
            branches:
              only: master
